require:
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.2
  Include:
    - '**/*.ruby'
    - '**/*.rake'
    - '**/*.rb'
    - '**/*.rsb'
    - '**/Rakefile'
    - '**/Gemfile'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 25

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

# required for travis/ci (symbolic links problem)
Style/ExpandPathArguments:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
