name: Redmine Git Hosting
description: A Redmine plugin which makes configuring your own Git hosting easy ;)
repository: https://github.com/jbox-web/redmine_git_hosting

github_user: jbox-web
github_repository: redmine_git_hosting

release:
  version: 5.0.0

author:
  name: JBox Web
  url: http://www.jbox-web.com/

license:
  name: MIT
  url: http://opensource.org/licenses/MIT

# If you leave this field blank, google analytics is not run.
google_analytics: UA-36504891-3
